### ISSUE TITLE
Config travis CI or another free CI

### ISSUE THREAD

**Issue by Zardoz89** [PhilippeSigaud/Pegged#276]
Config a travis CI, so could run the unit tests on every PR.

**Comment by Zardoz89** [comment]
With travis, and taking from vibed configuration, could be something similar to this : 

.travis.yml
```yml
language: d
dist: xenial

branches:
  only:
  - master

# Enable core dumps
before_script:
  - ulimit -c unlimited -S
  - sudo mkdir /cores/ && sudo chmod 777 /cores/
  - echo "/cores/%E.%p" | sudo tee /proc/sys/kernel/core_pattern

after_failure:
  - ./scripts/core-dump.sh

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.091.0,dub
  - dmd-2.090.1,dub
  - dmd-2.089.0,dub
  - ldc-1.18.0,dub
  - ldc-1.17.0,dub
  - dmd-beta,dub

matrix:
  include:
    - d: dmd

script: ./travis-ci.sh
after_success:
 - bash <(curl -s https://codecov.io/bash)

```
travis-ci.sh
```bash
#!/bin/bash

set -e -x -o pipefail

# test for successful release build
dub build -b release --compiler=$DC
dub clean --all-packages

# test for successful 32-bit build
if [ "$DC" == "dmd" ]; then
    dub build -b release --compiler=$DC --arch=x86
    dub clean --all-packages
fi

# Run unit tests
dub test --compiler=$DC
```
